# Generated by Django 4.0.3 on 2022-08-18 14:30

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('release_date', models.CharField(max_length=100, null=True)),
                ('cover', models.ImageField(upload_to='movie_covers')),
            ],
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', multiselectfield.db.fields.MultiSelectField(choices=[('10:00 AM', '10:00 AM'), ('12:00 PM', '12:00 PM'), ('2:00 PM', '2:00 PM'), ('4:00 PM', '4:00 PM'), ('6:30 PM', '6:00 PM')], max_length=41)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater', models.CharField(max_length=255, null=True)),
                ('movies', models.ManyToManyField(blank=True, null=True, through='movies.ShowTime', to='movies.movie')),
            ],
        ),
        migrations.AddField(
            model_name='showtime',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.theater'),
        ),
    ]
