# Generated by Django 4.0.3 on 2022-08-18 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theater',
            old_name='theater',
            new_name='theater_name',
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='theater',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='theater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.theater'),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.movie'),
        ),
    ]
