# Generated by Django 4.0.3 on 2022-08-20 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_seat_movie_ticket_price_movie_booked_seats'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookedtickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('movie_name', models.CharField(max_length=255)),
                ('number_of_tickets', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('selected_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BookedSeats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.movie')),
                ('showtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.showtime')),
            ],
        ),
    ]
