# Generated by Django 4.0.3 on 2022-08-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_bookedtickets_bookedseats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedtickets',
            name='selected_time',
            field=models.CharField(max_length=255),
        ),
    ]
