# Generated by Django 4.0.3 on 2022-08-20 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_bookedtickets_selected_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedtickets',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
