# Generated by Django 4.0.3 on 2022-08-20 17:54

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_bookedtickets_selected_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedtickets',
            name='booking_date',
            field=models.DateField(validators=[movies.models.bookedtickets.validate_date]),
        ),
    ]
