# Generated by Django 4.0.3 on 2022-08-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_bookedtickets_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedtickets',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
